apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  type: NodePort
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000  # Python app's default port (Flask/Django often use 5000/8000)
      nodePort: 30008
