apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      imagePullSecrets:
        - name: gitlab-registry-secret
      containers:
        - name: python-app
          image: registry.gitlab.com/test8042807/python-application:e87745af
          ports:
            - containerPort: 3000
          env:
            - name: ENV
              value: "production"
